---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: go-auth
  annotations:
    kubernetes.io/service-account.name: go-auth
type: kubernetes.io/service-account-token
